name: NekoAutoPack
version: 0.1.1
main: com.iaauto.IAAutoPlugin
api-version: '1.20.6'
description: Packages and pushes ItemsAdder generated.zip through local git.
author: NekoAutoPack

commands:
  nap:
    description: Runs NekoAutoPack commands.
    usage: /nap <help|start|push|reload>

permissions:
  nap.help:
    description: Allows /nap help.
    default: true
  nap.start:
    description: Allows /nap start.
    default: op
  nap.push:
    description: Allows /nap push.
    default: op
  nap.reload:
    description: Allows /nap reload.
    default: op
